name: Redis

services:
  Redis:
    container_name: redis
    image: redis/redis-stack-server:latest
    mem_limit: 700m
    env_file: [ env/redis.env ]
    environment:
      TZ: Asia/Shanghai
    network_mode: host
    restart: no
    healthcheck:
      test: [ "CMD-SHELL", "REDISCLI_AUTH=$$REDIS_PASSWORD redis-cli ping | grep PONG" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "2"