name: Redis

services:
  Redis:
    container_name: Redis
    image: redis:latest
    mem_limit: 700m
    environment:
      TZ: Asia/Shanghai
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: >-
      redis-server
      --requirepass "${REDIS_PASSWORD}"
      --ignore-warnings ARM64-COW-BUG
    network_mode: bridge
    ports:
      - "6379:6379/tcp"
    restart: no
    healthcheck:
      test: ["CMD-SHELL", "REDISCLI_AUTH=$$REDIS_PASSWORD redis-cli -p ${REDIS_PORT} ping | grep -q PONG"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "2"
