# Branch pattern
feature:
  - head-branch: ['^feature/']
fix:
  - head-branch: ['^fix/']
hotfix:
  - head-branch: ['^hotfix/']
release:
  - head-branch: ['^release/']

# Directory pattern
documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"

github-actions:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/**"

gradle:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.gradle"
          - "**/*.gradle.kts"
          - "gradle/**"

java:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.java"

kotlin:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.kt"
          - "**/*.kts"

devcontainer:
  - changed-files:
      - any-glob-to-any-file:
          - ".devcontainer/**"

docker:
  - changed-files:
      - any-glob-to-any-file:
          - "docker/**/*"

ai:
  - changed-files:
      - any-glob-to-any-file:
          - "ai/**/*"

assets:
  - changed-files:
      - any-glob-to-any-file:
          - "assets/**/*"
