name: CloudFlare-Mesh

services:
  cloudflare-mesh:
    container_name: CloudFlare-Mesh
    image: cloudflare/mesh:latest
    mem_limit: 128m
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      MESH_NODE_TOKEN: ${MESH_NODE_TOKEN}
      SRCNAT_ENABLED: "true"
    sysctls:
      net.ipv4.ip_forward: "1"
      net.ipv6.conf.all.forwarding: "1"
      net.ipv6.conf.default.forwarding: "1"
    volumes: [CloudFlareMesh-Data:/var/lib/cloudflare-warp]
    restart: unless-stopped

volumes:
  CloudFlareMesh-Data:
    name: CloudFlareMesh-Data
