name: Redis-Cluster

services:
  redis:
    container_name: Redis-Cluster
    image: redis/redis-stack-server:latest
    mem_limit: 700m
    environment:
      TZ: Asia/Shanghai
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_ARGS: >-
        --cluster-enabled yes
        --cluster-announce-ip ${CLUSTER_ANNOUNCE_IP}
        --cluster-announce-port ${REDIS_PORT}
        --cluster-announce-bus-port ${REDIS_CLUSTER_BUS_PORT}
        --requirepass ${REDIS_PASSWORD}
        --ignore-warnings ARM64-COW-BUG
    network_mode: bridge
    ports:
      - "6379:6379/tcp"
      - "16379:16379/tcp"
    restart: no
    healthcheck:
      test: [ "CMD-SHELL", "REDISCLI_AUTH=$$REDIS_PASSWORD redis-cli -p ${REDIS_PORT} ping | grep -q PONG"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "2"
