name: CloudFlare

services:
  CloudFlare:
    container_name: cloudflare-d
    image: cloudflare/cloudflared:latest
    mem_limit: 200m
    env_file: [ env/cloudflare.env ]
    environment:
      TZ: Asia/Shanghai
    command: [ "tunnel", "run" ]
    network_mode: host
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "cloudflared", "version" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "2"