name: RustDesk

services:
  RustDesk-Server:
    container_name: rustdesk-server
    image: rustdesk/rustdesk-server:latest
    command: hbbs
    mem_limit: 150m
    volumes: [ RustDesk-Data:/root ]
    network_mode: host
    depends_on:
      - RustDesk-Relay
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "hbbs", "-h"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "2"

  RustDesk-Relay:
    container_name: rustdesk-relay
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    mem_limit: 150m
    volumes: [ RustDesk-Data:/root ]
    network_mode: host
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "hbbr", "-h"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "2"

volumes:
  RustDesk-Data:
    name: RustDesk-Data