name: RabbitMQ

services:
  RabbitMQ:
    container_name: RabbitMQ
    image: rabbitmq:management
    mem_limit: 700m
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes: [RabbitMQ-Data:/var/lib/rabbitmq]
    network_mode: bridge
    ports:
      - "5672:5672/tcp"
      - "15672:15672/tcp"
    restart: no
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "2"

volumes:
  RabbitMQ-Data:
    name: RabbitMQ-Data
